### ISSUE TITLE
Better typing to SpyInstance type

### ISSUE THREAD

**Issue by abdulhadi-lababidi98** [fdc-viktor-luft/spy4js#8]
I was working on adding tests to react component, and the component basically called `FormSelectBranch` and it has the following props:
```
repositoryURLField: FormField<string>,
branchField: FormField<string>,
```

So inside the test file I did:
```
    beforeEach(() => {
        mockReactComponents_FormSelectBranch.FormSelectBranch.calls(MorfiTestUtils.Field);
    });
```

And the test introduced weird behaviours, after hour of debugging I realised the problem with my code, and to solve the problem I need to wrap the `MorfiTestUtils.Field`  function with another functions that pass the props properly:
```
        mockReactComponents_FormSelectBranch.FormSelectBranch.calls(
            ({ repositoryURLField }: any) => MorfiTestUtils.Field({ field: repositoryURLField }),
            ({ branchField }: any) => MorfiTestUtils.Field({ field: branchField })
        );
```

#### The expected behaviour:
I should get type error for the first code snippet

#### Suggested solution 
We can update the types of SpyInstance to be more safe, something like this:
```
type SpyInstance<T extends (...args: any) => any> = {
    calls: (...funcs: Array<(...params: Parameters<T>) => ReturnType<T>>) => SpyInstance<T>;
};
```
And we can do so for the other functions

**Comment by fdc-viktor-luft** [comment]
I didn't add type safety in first place, because it also adds a burden on the writer of a test that the provided function needs to fulfill the interface. That would make some "any" casts necessary in case you want to be less accurate.

However, also looking into the behavioral change of other test frameworks, it seems more beneficial to have it. As it would be a breaking change, I'll include it into the pending v4 release.
